In [1]:
import pandas as pd 
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
aplFile = '/Users/swethakolalapudi/Desktop/Reg_Data/AAPL.csv'
nasdaqFile = '/Users/swethakolalapudi/Desktop/Reg_Data/NASDAQ.csv'

In [3]:
apl = pd.read_csv(aplFile,sep=",",usecols=[0,6],names=['Date','apl'],header=0)
apl.head()

Date         apl
0  2017-01-03  120.826149
1  2016-12-01  115.320023
2  2016-11-01  110.042900
3  2016-10-03  112.472404
4  2016-09-01  111.987015

In [4]:
nasdaq = pd.read_csv(nasdaqFile,sep=",",usecols=[0,6],names=['Date','Nasdaq'],header=0)
apl['Nasdaq'] = nasdaq['Nasdaq']

apl.head()

Date         apl       Nasdaq
0  2017-01-03  120.826149  5614.790039
1  2016-12-01  115.320023  5383.120117
2  2016-11-01  110.042900  5323.680176
3  2016-10-03  112.472404  5189.140137
4  2016-09-01  111.987015  5312.000000

In [5]:
apl['Date'] = pd.to_datetime(apl['Date'], format='%Y-%m-%d')

In [6]:
apl = apl.sort_values(['Date'], ascending=[True])

In [7]:
returns = apl[['apl','Nasdaq']].pct_change()
returns.head()

apl    Nasdaq
120       NaN       NaN
119 -0.013064 -0.019392
118  0.098097  0.002272
117  0.074158  0.042719
116  0.214329  0.031456

In [8]:
returns = returns[1:]
returns.head()

apl    Nasdaq
119 -0.013064 -0.019392
118  0.098097  0.002272
117  0.074158  0.042719
116  0.214329  0.031456
115  0.007014 -0.000495

In [9]:
yData = returns['apl']
yData[:5]

119   -0.013064
118    0.098097
117    0.074158
116    0.214329
115    0.007014
Name: apl, dtype: float64

In [10]:
xData = returns['Nasdaq'].values.reshape(-1,1)
xData[:5]

array([[-0.0193918 ],
       [ 0.00227221],
       [ 0.04271907],
       [ 0.03145628],
       [-0.00049531]])

In [11]:
goodAplModel = LinearRegression()
goodAplModel.fit(xData,yData)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [12]:
goodAplModel.score(xData,yData)

0.45441827670601787

In [13]:
goodAplModel.predict(np.array([-0.1,0.05]).reshape(-1,1))

array([-0.10623334,  0.07490514])

In [14]:
goodAplModel.coef_

array([ 1.20758981])

In [ ]:
plt.scatter(xData, yData,  color='black')
plt.plot(xData, goodAplModel.predict(xData), color='blue',
         linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()