## Voting for Classification 

### We will be using the IRIS dataset 


In [1]:
#Lets import the libraries and datasets 
import numpy as np

from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split

import statistics as stat

c:\users\tatsa02\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
#Lets load the dataset
iris = datasets.load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
X = iris.data[:, [0, 2]]
y = iris.target

In [4]:
#Lets check the shape of our data 
print(X.shape)
print(y.shape)

(150, 2)
(150,)


In [5]:
#Output classes
list(iris.target_names)

['setosa', 'versicolor', 'virginica']

In [6]:
#Lets split our data in train and test 
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1)

In [7]:
#Lets check the shape 
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(112, 2)
(112,)
(38, 2)
(38,)


In [8]:
#We initialize the models
model1 = DecisionTreeClassifier(max_depth=4)
model2 = KNeighborsClassifier(n_neighbors=7)
model3 = SVC(kernel='rbf', probability=True)

In [9]:
#We then fit the models 
model1.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [10]:
model2.fit(X_train, y_train)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=7, p=2,
           weights='uniform')

In [11]:
model3.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

### Lets look at the accuracy for each model 

In [12]:
#The accuracy score for the first model is
score1=model1.score(X_test, y_test)
print(score1)

0.9736842105263158


In [13]:
#The accuracy score for the second model is
score2=model2.score(X_test, y_test)
print(score2)

1.0


In [14]:
#The accuracy score for the third model is
score3=model3.score(X_test, y_test)
print(score3)

0.9736842105263158


### Lets combine the models using voting in python 

In [15]:
#Lets find out what each model predicts 
pred1=model1.predict(X_test)
pred2=model2.predict(X_test)
pred3=model3.predict(X_test)

#Lets take the vote using the mode function 
final_pred = np.array([])
for i in range(0,len(X_test)):
    final_pred = np.append(final_pred, stat.mode([pred1[i], pred2[i], pred3[i]]))

In [16]:
X_test

array([[5.8, 1.2],
       [5.1, 3. ],
       [6.6, 4.4],
       [5.4, 1.3],
       [7.9, 6.4],
       [6.3, 4.7],
       [6.9, 5.1],
       [5.1, 1.9],
       [4.7, 1.6],
       [6.9, 5.7],
       [5.6, 4.2],
       [5.4, 1.7],
       [7.1, 5.9],
       [6.4, 4.5],
       [6. , 4.5],
       [4.4, 1.3],
       [5.8, 4. ],
       [5.6, 4.5],
       [5.4, 1.5],
       [5. , 1.2],
       [5.5, 4.4],
       [5.4, 4.5],
       [6.7, 5. ],
       [5. , 1.3],
       [7.2, 6. ],
       [5.7, 4.1],
       [5.5, 1.4],
       [5.1, 1.5],
       [6.1, 4.7],
       [6.3, 5. ],
       [6.1, 4.6],
       [7.7, 6.1],
       [5.6, 3.9],
       [6.4, 5.6],
       [5.8, 5.1],
       [5.3, 1.5],
       [5.5, 4. ],
       [5.2, 1.4]])

In [31]:
import pandas as pd
pd.concat([pd.DataFrame(pred1),pd.DataFrame(pred2),pd.DataFrame(pred3),pd.DataFrame(y_test)],axis=1)

0  0  0  0
0   0  0  0  0
1   1  1  1  1
2   1  1  1  1
3   0  0  0  0
4   2  2  2  2
5   1  1  1  1
6   2  2  2  2
7   0  0  0  0
8   0  0  0  0
9   2  2  2  2
10  1  1  1  1
11  0  0  0  0
12  2  2  2  2
13  1  1  1  1
14  1  1  1  1
15  0  0  0  0
16  1  1  1  1
17  1  1  1  1
18  0  0  0  0
19  0  0  0  0
20  1  1  1  1
21  1  1  1  1
22  2  1  2  1
23  0  0  0  0
24  2  2  2  2
25  1  1  1  1
26  0  0  0  0
27  0  0  0  0
28  1  1  1  1
29  2  2  2  2
30  1  1  1  1
31  2  2  2  2
32  1  1  1  1
33  2  2  2  2
34  2  2  2  2
35  0  0  0  0
36  1  1  1  1
37  0  0  0  0

In [20]:
final_pred

array([0., 1., 1., 0., 2., 1., 2., 0., 0., 2., 1., 0., 2., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 2., 0., 2., 1., 0., 0., 1., 2., 1., 2., 1., 2.,
       2., 0., 1., 0.])

### This is also called as a hard voting since we are using the model predictions to get the final combined prediction 

In [17]:
total=np.sum(y_test==final_pred)

print("Accuracy:",total,"/",len(final_pred),"* 100 =","{0:.3f}".format(total/len(final_pred)*100),"%")

Accuracy: 37 / 38 * 100 = 97.368 %


### Soft voting in python

In [37]:
spred1=model1.predict_proba(X_test)
spred2=model2.predict_proba(X_test)
spred3=model3.predict_proba(X_test)

finalpred=(spred1+spred2+spred3)/3

In [45]:
finalpred

array([[0.96714387, 0.016355  , 0.01650112],
       [0.02827664, 0.95339779, 0.01832557],
       [0.00505834, 0.99064273, 0.00429892],
       [0.98408866, 0.00792149, 0.00798984],
       [0.00844796, 0.02222799, 0.96932405],
       [0.00410281, 0.7858865 , 0.21001069],
       [0.00571022, 0.26801215, 0.72627763],
       [0.97870864, 0.01260468, 0.00868668],
       [0.98501298, 0.00772933, 0.00725769],
       [0.0038748 , 0.00522144, 0.99090376],
       [0.00336731, 0.97872751, 0.01790518],
       [0.9832026 , 0.00924341, 0.00755398],
       [0.00405579, 0.00550635, 0.99043787],
       [0.00430437, 0.9838484 , 0.01184723],
       [0.00374329, 0.91374819, 0.08250851],
       [0.98111363, 0.00958685, 0.00929952],
       [0.00386846, 0.99204301, 0.00408854],
       [0.00398201, 0.85288509, 0.1431329 ],
       [0.9852322 , 0.0076228 , 0.007145  ],
       [0.98662978, 0.00659946, 0.00677076],
       [0.00374495, 0.92580628, 0.07044877],
       [0.00406714, 0.7643898 , 0.23154306],
       [0.

In [46]:
finalpred.argmax(axis=1)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0], dtype=int32)

In [16]:
final_classes = finalpred.argmax(axis=-1) 
final_classes

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0])

In [47]:
y_test

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0])

In [17]:
total=np.sum([y_test[i]==final_classes[i] for i in range(len(final_classes))])

print("Accuracy:",total,"/",len(final_classes),"* 100 =","{0:.3f}".format(total/len(final_classes)*100),"%")

Accuracy: 37 / 38 * 100 = 97.368 %


### We can also use VotingClassifier from sklearn to combine the models

In [48]:
emodel = VotingClassifier(estimators=[('dt', model1), ('knn', model2),
                                    ('svc', model3)],
                        voting='soft')
emodel.fit(X_train, y_train)


VotingClassifier(estimators=[('dt', DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0....',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='soft', weights=None)

In [49]:
#The accuracy score for the ensemble model is
escore=emodel.score(X_test, y_test)
print(escore)

0.9736842105263158


c:\users\tatsa02\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
